/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthConfirmRouteImport } from './routes/auth/confirm'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignUpSuccessRouteImport } from './routes/auth/sign-up-success'
import { Route as AuthUpdatePasswordRouteImport } from './routes/auth/update-password'
import { Route as AuthenticatedBookmarksIndexRouteImport } from './routes/_authenticated/bookmarks/index'
import { Route as AuthenticatedBookmarksNewRouteImport } from './routes/_authenticated/bookmarks/new'
import { Route as AuthenticatedBookmarksUnreadRouteImport } from './routes/_authenticated/bookmarks/unread'
import { Route as AuthenticatedSessionsIdRouteImport } from './routes/_authenticated/sessions/$id'
import { Route as AuthenticatedTagsIdRouteImport } from './routes/_authenticated/tags/$id'
import { Route as ApiAiBookmarkRouteImport } from './routes/api/ai/bookmark'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpSuccessRoute = AuthSignUpSuccessRouteImport.update({
  id: '/auth/sign-up-success',
  path: '/auth/sign-up-success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUpdatePasswordRoute = AuthUpdatePasswordRouteImport.update({
  id: '/auth/update-password',
  path: '/auth/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBookmarksIndexRoute =
  AuthenticatedBookmarksIndexRouteImport.update({
    id: '/bookmarks/',
    path: '/bookmarks/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBookmarksNewRoute =
  AuthenticatedBookmarksNewRouteImport.update({
    id: '/bookmarks/new',
    path: '/bookmarks/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBookmarksUnreadRoute =
  AuthenticatedBookmarksUnreadRouteImport.update({
    id: '/bookmarks/unread',
    path: '/bookmarks/unread',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSessionsIdRoute = AuthenticatedSessionsIdRouteImport.update({
  id: '/sessions/$id',
  path: '/sessions/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTagsIdRoute = AuthenticatedTagsIdRouteImport.update({
  id: '/tags/$id',
  path: '/tags/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiAiBookmarkRoute = ApiAiBookmarkRouteImport.update({
  id: '/api/ai/bookmark',
  path: '/api/ai/bookmark',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/sign-up-success': typeof AuthSignUpSuccessRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/bookmarks/new': typeof AuthenticatedBookmarksNewRoute
  '/bookmarks/unread': typeof AuthenticatedBookmarksUnreadRoute
  '/sessions/$id': typeof AuthenticatedSessionsIdRoute
  '/tags/$id': typeof AuthenticatedTagsIdRoute
  '/api/ai/bookmark': typeof ApiAiBookmarkRoute
  '/bookmarks/': typeof AuthenticatedBookmarksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/sign-up-success': typeof AuthSignUpSuccessRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/bookmarks/new': typeof AuthenticatedBookmarksNewRoute
  '/bookmarks/unread': typeof AuthenticatedBookmarksUnreadRoute
  '/sessions/$id': typeof AuthenticatedSessionsIdRoute
  '/tags/$id': typeof AuthenticatedTagsIdRoute
  '/api/ai/bookmark': typeof ApiAiBookmarkRoute
  '/bookmarks': typeof AuthenticatedBookmarksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/sign-up-success': typeof AuthSignUpSuccessRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/_authenticated/bookmarks/new': typeof AuthenticatedBookmarksNewRoute
  '/_authenticated/bookmarks/unread': typeof AuthenticatedBookmarksUnreadRoute
  '/_authenticated/sessions/$id': typeof AuthenticatedSessionsIdRoute
  '/_authenticated/tags/$id': typeof AuthenticatedTagsIdRoute
  '/api/ai/bookmark': typeof ApiAiBookmarkRoute
  '/_authenticated/bookmarks/': typeof AuthenticatedBookmarksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/auth/confirm'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/sign-up'
    | '/auth/sign-up-success'
    | '/auth/update-password'
    | '/bookmarks/new'
    | '/bookmarks/unread'
    | '/sessions/$id'
    | '/tags/$id'
    | '/api/ai/bookmark'
    | '/bookmarks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/auth/confirm'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/sign-up'
    | '/auth/sign-up-success'
    | '/auth/update-password'
    | '/bookmarks/new'
    | '/bookmarks/unread'
    | '/sessions/$id'
    | '/tags/$id'
    | '/api/ai/bookmark'
    | '/bookmarks'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/auth/confirm'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/sign-up'
    | '/auth/sign-up-success'
    | '/auth/update-password'
    | '/_authenticated/bookmarks/new'
    | '/_authenticated/bookmarks/unread'
    | '/_authenticated/sessions/$id'
    | '/_authenticated/tags/$id'
    | '/api/ai/bookmark'
    | '/_authenticated/bookmarks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthConfirmRoute: typeof AuthConfirmRoute
  AuthErrorRoute: typeof AuthErrorRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthSignUpSuccessRoute: typeof AuthSignUpSuccessRoute
  AuthUpdatePasswordRoute: typeof AuthUpdatePasswordRoute
  ApiAiBookmarkRoute: typeof ApiAiBookmarkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up-success': {
      id: '/auth/sign-up-success'
      path: '/auth/sign-up-success'
      fullPath: '/auth/sign-up-success'
      preLoaderRoute: typeof AuthSignUpSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/update-password': {
      id: '/auth/update-password'
      path: '/auth/update-password'
      fullPath: '/auth/update-password'
      preLoaderRoute: typeof AuthUpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bookmarks/': {
      id: '/_authenticated/bookmarks/'
      path: '/bookmarks'
      fullPath: '/bookmarks/'
      preLoaderRoute: typeof AuthenticatedBookmarksIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bookmarks/new': {
      id: '/_authenticated/bookmarks/new'
      path: '/bookmarks/new'
      fullPath: '/bookmarks/new'
      preLoaderRoute: typeof AuthenticatedBookmarksNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bookmarks/unread': {
      id: '/_authenticated/bookmarks/unread'
      path: '/bookmarks/unread'
      fullPath: '/bookmarks/unread'
      preLoaderRoute: typeof AuthenticatedBookmarksUnreadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sessions/$id': {
      id: '/_authenticated/sessions/$id'
      path: '/sessions/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof AuthenticatedSessionsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tags/$id': {
      id: '/_authenticated/tags/$id'
      path: '/tags/$id'
      fullPath: '/tags/$id'
      preLoaderRoute: typeof AuthenticatedTagsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/ai/bookmark': {
      id: '/api/ai/bookmark'
      path: '/api/ai/bookmark'
      fullPath: '/api/ai/bookmark'
      preLoaderRoute: typeof ApiAiBookmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedBookmarksNewRoute: typeof AuthenticatedBookmarksNewRoute
  AuthenticatedBookmarksUnreadRoute: typeof AuthenticatedBookmarksUnreadRoute
  AuthenticatedSessionsIdRoute: typeof AuthenticatedSessionsIdRoute
  AuthenticatedTagsIdRoute: typeof AuthenticatedTagsIdRoute
  AuthenticatedBookmarksIndexRoute: typeof AuthenticatedBookmarksIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedBookmarksNewRoute: AuthenticatedBookmarksNewRoute,
  AuthenticatedBookmarksUnreadRoute: AuthenticatedBookmarksUnreadRoute,
  AuthenticatedSessionsIdRoute: AuthenticatedSessionsIdRoute,
  AuthenticatedTagsIdRoute: AuthenticatedTagsIdRoute,
  AuthenticatedBookmarksIndexRoute: AuthenticatedBookmarksIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthConfirmRoute: AuthConfirmRoute,
  AuthErrorRoute: AuthErrorRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthSignUpSuccessRoute: AuthSignUpSuccessRoute,
  AuthUpdatePasswordRoute: AuthUpdatePasswordRoute,
  ApiAiBookmarkRoute: ApiAiBookmarkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
